var data = [
    {
        name: 'zapas1',
        image: 'imagenes/zapa1.jpg',
        basicPrice: 1500,
        qty: 0,
        id: 01,
        description: 'description',
        partialViewDescription: '',
        partialViewCatalogue: '',
        partialViewBill: '',
        bill: '',
    },
    {
        name: 'zapas2',
        image: 'imagenes/zapas2.jpg',
        basicPrice: 1500,
        qty: 0,
        id: 01,
        description: 'description',
        partialViewDescription: '',
        partialViewCatalogue: '',
        partialViewBill: '',
        bill: '',
    },
]